#!/bin/bash


if [[ -z "${TIMEOUT}" ]]; then
	MY_TIMEOUT=90
else
	MY_TIMEOUT="${TIMEOUT}"
fi

# Remove this after debugging and pipe stderr to /dev/null
exec 2>/dev/null

timeout -k1 ${MY_TIMEOUT} stdbuf -i0 -o0 -e0 vmips -o memsize=2097152 $1
